# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MoUUlUp2qoagLeo9ronSj_Njp4tssFme
"""

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import uuid


def doAnalysis(symbol = "TCELL.IS", start_date = "2022-01-01", end_date = "2023-01-01"):

    data = yf.download(symbol, start=start_date, end=end_date)

    data = data['Close'].values.reshape(-1, 1)

    scaler = MinMaxScaler(feature_range=(0, 1))
    data_scaled = scaler.fit_transform(data)

    lookback = 50
    X, y = [], []

    for i in range(len(data_scaled) - lookback):
        X.append(data_scaled[i:i+lookback, 0])
        y.append(data_scaled[i+lookback, 0])

    X, y = np.array(X), np.array(y)

    split_ratio = 0.8
    split_index = int(len(X) * split_ratio)
    X_train, X_test, y_train, y_test = X[:split_index], X[split_index:], y[:split_index], y[split_index:]
    #LSTM modeli
    model = Sequential()
    model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1], 1)))
    model.add(LSTM(units=50))
    model.add(Dense(units=1))
    model.compile(optimizer='adam', loss='mean_squared_error')

    model.fit(X_train, y_train, epochs=50, batch_size=8)

    predictions = model.predict(X_test)
    predictions = scaler.inverse_transform(predictions)
    y_test = scaler.inverse_transform(y_test.reshape(-1, 1))

    plt.figure(figsize=(8, 4))
    plt.plot(predictions, label='Tahminler', linewidth=1.5)
    plt.plot(y_test, label='Gerçek Değerler', linewidth=1.5)
    plt.legend()
    plt.title('TCELL.IS Hisse Senedi Fiyat Tahmini')
    plt.xlabel('Günler')
    plt.ylabel('Kapanış Fiyatı')
    plt.show()
    fileName = 'temp/'+ uuid.uuid4()+'.png'
    plt.savefig(fileName)
    return fileName

    """Örneğin, Türkiye'de bulunan Turkcell hisse senedi için TCELL.IS sembolünü, Koç Holding için KCHOL.IS sembolünü, Garanti Bankası için GARAN.IS sembolünü kullanabilirsiniz. Bu semboller, Yahoo Finance tarafından tanımlanan standart sembollerdir."""